git clone -b 8.0 https://github.com/oca/account-analytic
git clone -b 8.0 https://github.com/OCA/account-closing
git clone -b 8.0 https://github.com/oca/account-invoicing
git clone -b 8.0 https://github.com/oca/account-financial-reporting
git clone -b 8.0 https://github.com/oca/account-financial-tools 
git clone -b 8.0 https://github.com/oca/contract
git clone -b 8.0 https://github.com/oca/intrastat
git clone -b 8.0 https://github.com/oca/mis-builder
git clone -b 8.0 https://github.com/oca/operating-unit
git clone -b 8.0 https://github.com/oca/partner-contact
git clone -b 8.0 https://github.com/OCA/purchase-workflow
git clone -b 8.0 https://github.com/oca/product-attribute
git clone -b 8.0 https://github.com/oca/reporting-engine
git clone -b 8.0 https://github.com/OCA/sale-workflow
git clone -b 8.0 https://github.com/oca/server-tools
git clone -b 8.0 https://github.com/oca/stock-logistics-transport
git clone -b 8.0 https://github.com/oca/stock-logistics-warehouse
git clone -b 8.0 https://github.com/oca/stock-logistics-workflow
git clone -b 8.0 https://github.com/oca/web
git clone -b 8.0 https://github.com/open-synergy/opnsynid-account-closing
git clone -b 8.0 https://github.com/open-synergy/opnsynid-account-invoicing
git clone -b 8.0 https://github.com/open-synergy/opnsynid-accounting-report
git clone -b 8.0 https://github.com/open-synergy/opnsynid-edii
git clone -b 8.0 https://github.com/open-synergy/opnsynid-l10n-indonesia
git clone -b 8.0 https://github.com/open-synergy/opnsynid-manufacture
git clone -b 8.0 https://github.com/open-synergy/opnsynid-odoo-curated
git clone -b 8.0 https://github.com/open-synergy/opnsynid-operating-unit
git clone -b 8.0 https://github.com/open-synergy/opnsynid-partner-contact
git clone -b 8.0 https://github.com/open-synergy/opnsynid-purchase-workflow
git clone -b 8.0 https://github.com/open-synergy/opnsynid-product-attribute
git clone -b 8.0 https://github.com/open-synergy/opnsynid-sale-workflow
git clone -b 8.0 https://github.com/open-synergy/opnsynid-server-tools
git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-logistics-warehouse
git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-logistics-workflow
git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-reporting
git clone -b 8.0 https://github.com/odoomrp/odoomrp-utils.git
git clone -b 8.0 https://github.com/odoomrp/odoomrp-wip
git clone https://github.com/oktovan/invent2.git
