sudo git clone -b 8.0 https://github.com/oca/account-analytic
sudo git clone -b 8.0 https://github.com/OCA/account-closing
sudo git clone -b 8.0 https://github.com/oca/account-invoicing
sudo git clone -b 8.0 https://github.com/oca/account-financial-reporting
sudo git clone -b 8.0 https://github.com/oca/account-financial-tools 
sudo git clone -b 8.0 https://github.com/oca/contract
sudo git clone -b 8.0 https://github.com/oca/intrastat
sudo git clone -b 8.0 https://github.com/oca/mis-builder
sudo git clone -b 8.0 https://github.com/oca/manufacture
sudo git clone -b 8.0 https://github.com/oca/operating-unit
sudo git clone -b 8.0 https://github.com/oca/partner-contact
sudo git clone -b 8.0 https://github.com/OCA/purchase-workflow
sudo git clone -b 8.0 https://github.com/oca/product-attribute
sudo git clone -b 8.0 https://github.com/oca/reporting-engine
sudo git clone -b 8.0 https://github.com/OCA/sale-workflow
sudo git clone -b 8.0 https://github.com/oca/server-tools
sudo git clone -b 8.0 https://github.com/oca/stock-logistics-transport
sudo git clone -b 8.0 https://github.com/oca/stock-logistics-warehouse
sudo git clone -b 8.0 https://github.com/oca/stock-logistics-workflow
sudo git clone -b 8.0 https://github.com/oca/web
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-account-closing
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-account-invoicing
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-accounting-report
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-edii
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-hr
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-l10n-indonesia
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-manufacture
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-odoo-curated
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-operating-unit
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-partner-contact
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-purchase-workflow
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-product-attribute
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-sale-workflow
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-server-tools
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-logistics-warehouse
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-logistics-workflow
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-stock-reporting
sudo git clone -b 8.0 https://github.com/odoomrp/odoomrp-utils.git
sudo git clone -b 8.0 https://github.com/odoomrp/odoomrp-wip
sudo git clone -b 8.0 https://github.com/OdooCommunityWidgets/website_multi_image.git
sudo git clone -b 8.0 https://github.com/OCA/website
sudo git clone https://github.com/oktovan/invent2.git
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-l10n-indonesia-report
sudo git clone -b 8.0 https://github.com/open-synergy/opnsynid-sale-reporting
sudo git clone -b 8.0 https://github.com/OCA/product-variant
